export secretManagerURL =  "https://secrets.extensivlyon.coffee"
# export secretManagerURL = "https://localhost:6999" 
export dataManagerURL = "https://data.extensivlyon.coffee"
# dataManagerURL: "https://localhost:6999" 
export secretKeyHex =  ""
export publicKeyHex =  ""
